/* ===== Intermediate reader vocabulary (the words the story needs) ===== */
const VOCAB_READER={
/* --- time, place, basic nouns --- */
"天":{p:"tiān",d:"day; sky",l:"reader"},
"外面":{p:"wàimiàn",d:"outside",l:"reader"},
"面":{p:"miàn",d:"face; side; surface",l:"reader"},
"窗户":{p:"chuānghu",d:"window",l:"reader"},
"窗":{p:"chuāng",d:"window",l:"reader"},
"雨":{p:"yǔ",d:"rain",l:"reader"},
"客厅":{p:"kètīng",d:"living room",l:"reader"},
"会议室":{p:"huìyìshì",d:"meeting room",l:"reader"},
"酒馆":{p:"jiǔguǎn",d:"bar; tavern",l:"reader"},
"墙":{p:"qiáng",d:"wall",l:"reader"},
"长椅":{p:"chángyǐ",d:"bench",l:"reader"},
"石头":{p:"shítou",d:"stone; rock",l:"reader"},
"树叶":{p:"shùyè",d:"leaves",l:"reader"},
"风":{p:"fēng",d:"wind",l:"reader"},
"光":{p:"guāng",d:"light",l:"reader"},
"月":{p:"yuè",d:"month; moon",l:"reader"},
"今年":{p:"jīnnián",d:"this year",l:"reader"},
"前":{p:"qián",d:"before; front; ago",l:"reader"},
"以前":{p:"yǐqián",d:"before; previously",l:"reader"},
"之前":{p:"zhīqián",d:"before; prior to",l:"reader"},
"以后":{p:"yǐhòu",d:"after; later",l:"reader"},
"以为":{p:"yǐwéi",d:"to assume (wrongly)",l:"reader"},
"刚":{p:"gāng",d:"just; just now",l:"reader"},
"左右":{p:"zuǒyòu",d:"about; approximately",l:"reader"},
"秒":{p:"miǎo",d:"second",l:"reader"},
"钟":{p:"zhōng",d:"clock; o'clock",l:"reader"},
"晚":{p:"wǎn",d:"late; evening",l:"reader"},
"半空中":{p:"bànkōngzhōng",d:"in mid-air",l:"reader"},
"中":{p:"zhōng",d:"middle; in; among",l:"reader"},
"边":{p:"biān",d:"side; edge",l:"reader"},
"南边":{p:"nánbian",d:"the south side",l:"reader"},
"一辈子":{p:"yíbèizi",d:"a whole lifetime",l:"reader"},
"距离":{p:"jùlí",d:"distance",l:"reader"},
"黑暗":{p:"hēi'àn",d:"darkness",l:"reader"},

/* --- work & things --- */
"方案":{p:"fāng'àn",d:"proposal; plan",l:"reader"},
"客户":{p:"kèhù",d:"client; customer",l:"reader"},
"创意":{p:"chuàngyì",d:"creative idea; creative",l:"reader"},
"总监":{p:"zǒngjiān",d:"director (job title)",l:"reader"},
"团队":{p:"tuánduì",d:"team",l:"reader"},
"工资":{p:"gōngzī",d:"salary; wages",l:"reader"},
"屏幕":{p:"píngmù",d:"screen",l:"reader"},
"电话":{p:"diànhuà",d:"telephone; phone call",l:"reader"},
"页":{p:"yè",d:"page",l:"reader"},
"句":{p:"jù",d:"sentence; (measure word for speech)",l:"reader"},
"话":{p:"huà",d:"words; speech; remark",l:"reader"},
"事":{p:"shì",d:"matter; thing; business",l:"reader"},
"鞋":{p:"xié",d:"shoes",l:"reader"},
"衣服":{p:"yīfu",d:"clothes",l:"reader"},
"上衣":{p:"shàngyī",d:"shirt; upper garment",l:"reader"},
"杯":{p:"bēi",d:"cup; glass",l:"reader"},
"根":{p:"gēn",d:"(measure word: long thin things)",l:"reader"},
"行":{p:"háng",d:"line; row; trade/profession (also read xíng: to walk; to go; OK)",l:"reader"},
"字":{p:"zì",d:"character; word",l:"reader"},

/* --- body & gesture --- */
"手":{p:"shǒu",d:"hand",l:"reader"},
"手指":{p:"shǒuzhǐ",d:"finger",l:"reader"},
"手臂":{p:"shǒubì",d:"arm",l:"reader"},
"头":{p:"tóu",d:"head",l:"reader"},
"身":{p:"shēn",d:"body",l:"reader"},
"背":{p:"bèi",d:"back; to turn one's back",l:"reader"},
"抬":{p:"tái",d:"to lift; to raise",l:"reader"},
"低":{p:"dī",d:"low; to lower",l:"reader"},
"转":{p:"zhuǎn",d:"to turn",l:"reader"},
"停":{p:"tíng",d:"to stop; to pause",l:"reader"},
"碰":{p:"pèng",d:"to touch; to bump",l:"reader"},
"抖":{p:"dǒu",d:"to tremble; to shake",l:"reader"},
"伸":{p:"shēn",d:"to stretch out; to extend",l:"reader"},
"指":{p:"zhǐ",d:"to point at",l:"reader"},
"睁":{p:"zhēng",d:"to open (eyes)",l:"reader"},
"闭":{p:"bì",d:"to close; to shut",l:"reader"},
"躺":{p:"tǎng",d:"to lie down",l:"reader"},
"闻":{p:"wén",d:"to smell",l:"reader"},
"按":{p:"àn",d:"to press",l:"reader"},
"灭":{p:"miè",d:"to put out; to extinguish",l:"reader"},
"吹":{p:"chuī",d:"to blow",l:"reader"},
"掉":{p:"diào",d:"to fall; to drop; (away)",l:"reader"},
"挂":{p:"guà",d:"to hang; to hang up",l:"reader"},
"跑":{p:"pǎo",d:"to run",l:"reader"},
"步":{p:"bù",d:"step; pace",l:"reader"},
"赶":{p:"gǎn",d:"to rush; to catch (a train)",l:"reader"},
"算":{p:"suàn",d:"to calculate; to count",l:"reader"},
"改":{p:"gǎi",d:"to change; to revise",l:"reader"},
"删":{p:"shān",d:"to delete",l:"reader"},
"响":{p:"xiǎng",d:"to ring; to sound",l:"reader"},
"隔":{p:"gé",d:"to separate; at a distance of",l:"reader"},
"约":{p:"yuē",d:"to arrange to meet",l:"reader"},
"活":{p:"huó",d:"to live; alive",l:"reader"},
"死":{p:"sǐ",d:"to die; dead",l:"reader"},
"生":{p:"shēng",d:"to be born; to happen; raw",l:"reader"},
"发生":{p:"fāshēng",d:"to happen; to occur",l:"reader"},
"通过":{p:"tōngguò",d:"to pass; to approve; through",l:"reader"},
"超过":{p:"chāoguò",d:"to exceed; more than",l:"reader"},
"剩下":{p:"shèngxià",d:"to be left over; to remain",l:"reader"},
"想起":{p:"xiǎngqǐ",d:"to remember; to think of",l:"reader"},
"起":{p:"qǐ",d:"to rise; up",l:"reader"},
"成":{p:"chéng",d:"to become; into",l:"reader"},
"谈":{p:"tán",d:"to talk; to discuss",l:"reader"},
"值得":{p:"zhíde",d:"to be worth it",l:"reader"},

/* --- feeling & description --- */
"感觉":{p:"gǎnjué",d:"feeling; to feel",l:"reader"},
"表情":{p:"biǎoqíng",d:"facial expression",l:"reader"},
"平静":{p:"píngjìng",d:"calm; composed",l:"reader"},
"陌生":{p:"mòshēng",d:"unfamiliar; strange",l:"reader"},
"空":{p:"kōng",d:"empty; hollow",l:"reader"},
"乱":{p:"luàn",d:"messy; chaotic",l:"reader"},
"淡":{p:"dàn",d:"faint; light; bland",l:"reader"},
"味":{p:"wèi",d:"smell; taste",l:"reader"},
"沉":{p:"chén",d:"to sink; heavy",l:"reader"},
"准":{p:"zhǔn",d:"accurate; precise",l:"reader"},
"老实":{p:"lǎoshi",d:"honest; well-behaved",l:"reader"},
"自私":{p:"zìsī",d:"selfish",l:"reader"},
"勇敢":{p:"yǒnggǎn",d:"brave",l:"reader"},
"错误":{p:"cuòwù",d:"mistake; error",l:"reader"},
"瞎":{p:"xiā",d:"blind",l:"reader"},
"亮":{p:"liàng",d:"bright; to light up",l:"reader"},
"全":{p:"quán",d:"whole; entirely",l:"reader"},
"整个":{p:"zhěnggè",d:"the whole; entire",l:"reader"},
"大部分":{p:"dàbùfen",d:"most; the majority",l:"reader"},
"所有":{p:"suǒyǒu",d:"all",l:"reader"},
"一切":{p:"yíqiè",d:"everything; all",l:"reader"},
"任何":{p:"rènhé",d:"any; whatever",l:"reader"},
"另":{p:"lìng",d:"another; other",l:"reader"},
"也许":{p:"yěxǔ",d:"maybe; perhaps",l:"reader"},
"到底":{p:"dàodǐ",d:"after all; on earth",l:"reader"},
"真正":{p:"zhēnzhèng",d:"real; truly",l:"reader"},
"从头到尾":{p:"cóng tóu dào wěi",d:"from start to finish",l:"reader"},
"同一":{p:"tóngyī",d:"the same",l:"reader"},
"挺":{p:"tǐng",d:"quite; rather",l:"reader"},
"寸":{p:"cùn",d:"inch",l:"reader"},
"遍":{p:"biàn",d:"(measure word: times, rounds)",l:"reader"},
"第":{p:"dì",d:"(ordinal prefix: -th)",l:"reader"},
"样":{p:"yàng",d:"kind; manner; appearance",l:"reader"},
"这么":{p:"zhème",d:"so; like this",l:"reader"},
"才":{p:"cái",d:"only then; not until",l:"reader"},
"当":{p:"dāng",d:"when; to serve as",l:"reader"},
"该":{p:"gāi",d:"should; ought to",l:"reader"},
"可怕":{p:"kěpà",d:"terrifying; frightening",l:"reader"},
"怕":{p:"pà",d:"to fear; to be afraid",l:"reader"},
"满":{p:"mǎn",d:"full",l:"reader"},
"们":{p:"men",d:"(plural marker for people)",l:"reader"},
"没":{p:"méi",d:"not; have not",l:"reader"},
"打":{p:"dǎ",d:"to hit; to make (a call); to play",l:"reader"},
"电":{p:"diàn",d:"electricity",l:"reader"},
"妈":{p:"mā",d:"mom",l:"reader"},
"老婆":{p:"lǎopo",d:"wife",l:"reader"},
"嗯":{p:"èn",d:"(mm; uh-huh)",l:"reader"},
"哦":{p:"ó",d:"(oh)",l:"reader"},
"陈":{p:"Chén",d:"Chen (surname)",l:"reader"},
"加":{p:"jiā",d:"to add",l:"reader"},
"软":{p:"ruǎn",d:"soft",l:"reader"},
"今":{p:"jīn",d:"now; present",l:"reader"},
"子":{p:"zi",d:"(noun suffix); child",l:"reader"},
"室":{p:"shì",d:"room",l:"reader"},
"意":{p:"yì",d:"meaning; intention",l:"reader"},
"部":{p:"bù",d:"part; section",l:"reader"},
"以":{p:"yǐ",d:"with; by means of",l:"reader"},
"之":{p:"zhī",d:"(classical possessive particle)",l:"reader"},
"正":{p:"zhèng",d:"exactly; upright; in the middle of",l:"reader"},
"同":{p:"tóng",d:"same; together with",l:"reader"},
"可":{p:"kě",d:"can; but",l:"reader"},
"工":{p:"gōng",d:"work; labor",l:"reader"},
"资":{p:"zī",d:"funds; resources",l:"reader"},
"队":{p:"duì",d:"team; line",l:"reader"},
"团":{p:"tuán",d:"group; regiment",l:"reader"},
"椅":{p:"yǐ",d:"chair",l:"reader"},
"叶":{p:"yè",d:"leaf",l:"reader"},
"尾":{p:"wěi",d:"tail; end",l:"reader"},
"勇":{p:"yǒng",d:"brave",l:"reader"},
"敢":{p:"gǎn",d:"to dare",l:"reader"},
"私":{p:"sī",d:"private; selfish",l:"reader"},
"自":{p:"zì",d:"self; from",l:"reader"},
"误":{p:"wù",d:"error; to miss",l:"reader"},
"切":{p:"qiè",d:"(in 一切: all); to cut",l:"reader"},
"任":{p:"rèn",d:"to allow; any",l:"reader"},
"何":{p:"hé",d:"what; how",l:"reader"},
"许":{p:"xǔ",d:"to permit; perhaps",l:"reader"},
"暗":{p:"àn",d:"dark",l:"reader"},
"臂":{p:"bì",d:"arm",l:"reader"},
"衣":{p:"yī",d:"clothing",l:"reader"},
"石":{p:"shí",d:"stone",l:"reader"},
"结":{p:"jié",d:"to tie; to conclude",l:"reader"},
"实":{p:"shí",d:"real; solid",l:"reader"},
"底":{p:"dǐ",d:"bottom; end",l:"reader"},
"客":{p:"kè",d:"guest; customer",l:"reader"},
"户":{p:"hù",d:"household; account",l:"reader"},
"方":{p:"fāng",d:"square; direction; method",l:"reader"},
"案":{p:"àn",d:"case; plan; record",l:"reader"},
"厅":{p:"tīng",d:"hall; large room",l:"reader"},
"馆":{p:"guǎn",d:"establishment; venue",l:"reader"},
"创":{p:"chuàng",d:"to create",l:"reader"},
"监":{p:"jiān",d:"to supervise",l:"reader"},
"总":{p:"zǒng",d:"always; general; chief",l:"reader"},
"么":{p:"me",d:"(question/adverbial suffix)",l:"reader"},
"所":{p:"suǒ",d:"place; (nominalizing particle)",l:"reader"},
"左":{p:"zuǒ",d:"left",l:"reader"},
"右":{p:"yòu",d:"right",l:"reader"},
"辈":{p:"bèi",d:"generation; lifetime",l:"reader"},
"距":{p:"jù",d:"distance from",l:"reader"},
"平":{p:"píng",d:"flat; calm; level",l:"reader"},
"静":{p:"jìng",d:"quiet; still",l:"reader"},
"表":{p:"biǎo",d:"surface; to express; watch",l:"reader"},
"超":{p:"chāo",d:"to exceed; super-",l:"reader"},
"屏":{p:"píng",d:"screen",l:"reader"},
"幕":{p:"mù",d:"curtain; screen",l:"reader"},
"值":{p:"zhí",d:"value; worth",l:"reader"},
"陌":{p:"mò",d:"unfamiliar",l:"reader"},
"整":{p:"zhěng",d:"whole; to tidy",l:"reader"}
};
