/* ===== HSK 3 additions (205 words) ===== */
const VOCAB_HSK3={
"阿姨":{p:"āyí",d:"aunt; auntie (older woman)",l:"HSK 3"},
"啊":{p:"a",d:"(particle: ah, oh)",l:"HSK 3"},
"矮":{p:"ǎi",d:"short (in height)",l:"HSK 3"},
"爱好":{p:"àihào",d:"hobby; interest",l:"HSK 3"},
"把":{p:"bǎ",d:"(particle marking the object)",l:"HSK 3"},
"班":{p:"bān",d:"class; shift; work",l:"HSK 3"},
"搬":{p:"bān",d:"to move; to carry",l:"HSK 3"},
"办法":{p:"bànfǎ",d:"way; method; solution",l:"HSK 3"},
"包":{p:"bāo",d:"bag; to wrap",l:"HSK 3"},
"北方":{p:"běifāng",d:"the north",l:"HSK 3"},
"被":{p:"bèi",d:"(passive marker: by); quilt",l:"HSK 3"},
"鼻子":{p:"bízi",d:"nose",l:"HSK 3"},
"比较":{p:"bǐjiào",d:"rather; comparatively; to compare",l:"HSK 3"},
"比赛":{p:"bǐsài",d:"match; competition",l:"HSK 3"},
"笔记本":{p:"bǐjìběn",d:"notebook; laptop",l:"HSK 3"},
"必须":{p:"bìxū",d:"must; have to",l:"HSK 3"},
"变化":{p:"biànhuà",d:"change",l:"HSK 3"},
"别人":{p:"biéren",d:"other people; someone else",l:"HSK 3"},
"冰箱":{p:"bīngxiāng",d:"refrigerator",l:"HSK 3"},
"参加":{p:"cānjiā",d:"to take part in; to attend",l:"HSK 3"},
"草":{p:"cǎo",d:"grass",l:"HSK 3"},
"差":{p:"chà",d:"bad; poor; to lack",l:"HSK 3"},
"衬衫":{p:"chènshān",d:"shirt",l:"HSK 3"},
"成绩":{p:"chéngjì",d:"grade; result; achievement",l:"HSK 3"},
"除了":{p:"chúle",d:"except; besides; apart from",l:"HSK 3"},
"船":{p:"chuán",d:"boat; ship",l:"HSK 3"},
"春":{p:"chūn",d:"spring (season)",l:"HSK 3"},
"词典":{p:"cídiǎn",d:"dictionary",l:"HSK 3"},
"聪明":{p:"cōngming",d:"clever; smart",l:"HSK 3"},
"打扫":{p:"dǎsǎo",d:"to clean; to sweep",l:"HSK 3"},
"带":{p:"dài",d:"to bring; to carry; belt",l:"HSK 3"},
"地":{p:"de",d:"(adverbial particle)",l:"HSK 3"},
"电子邮件":{p:"diànzǐ yóujiàn",d:"email",l:"HSK 3"},
"东":{p:"dōng",d:"east",l:"HSK 3"},
"冬":{p:"dōng",d:"winter",l:"HSK 3"},
"动物":{p:"dòngwù",d:"animal",l:"HSK 3"},
"短":{p:"duǎn",d:"short (in length)",l:"HSK 3"},
"段":{p:"duàn",d:"(measure word: section, stretch, period)",l:"HSK 3"},
"锻炼":{p:"duànliàn",d:"to exercise; to work out",l:"HSK 3"},
"多么":{p:"duōme",d:"how; so (exclamatory)",l:"HSK 3"},
"耳朵":{p:"ěrduo",d:"ear",l:"HSK 3"},
"发烧":{p:"fāshāo",d:"to have a fever",l:"HSK 3"},
"发现":{p:"fāxiàn",d:"to discover; to find out",l:"HSK 3"},
"方便":{p:"fāngbiàn",d:"convenient",l:"HSK 3"},
"放":{p:"fàng",d:"to put; to place; to let go",l:"HSK 3"},
"分":{p:"fēn",d:"minute; point; to divide",l:"HSK 3"},
"复习":{p:"fùxí",d:"to review; to revise",l:"HSK 3"},
"感兴趣":{p:"gǎn xìngqù",d:"to be interested in",l:"HSK 3"},
"感冒":{p:"gǎnmào",d:"to catch a cold",l:"HSK 3"},
"刚才":{p:"gāngcái",d:"just now; a moment ago",l:"HSK 3"},
"个子":{p:"gèzi",d:"height; build",l:"HSK 3"},
"跟":{p:"gēn",d:"with; to follow",l:"HSK 3"},
"根据":{p:"gēnjù",d:"according to; based on",l:"HSK 3"},
"更":{p:"gèng",d:"even more; still more",l:"HSK 3"},
"公斤":{p:"gōngjīn",d:"kilogram",l:"HSK 3"},
"公园":{p:"gōngyuán",d:"park",l:"HSK 3"},
"刮风":{p:"guāfēng",d:"to be windy",l:"HSK 3"},
"关系":{p:"guānxi",d:"relationship; connections",l:"HSK 3"},
"关心":{p:"guānxīn",d:"to care about",l:"HSK 3"},
"关于":{p:"guānyú",d:"about; regarding",l:"HSK 3"},
"国家":{p:"guójiā",d:"country; nation",l:"HSK 3"},
"过去":{p:"guòqù",d:"the past; to go over",l:"HSK 3"},
"害怕":{p:"hàipà",d:"to be afraid; to fear",l:"HSK 3"},
"黑板":{p:"hēibǎn",d:"blackboard",l:"HSK 3"},
"后来":{p:"hòulái",d:"later; afterwards",l:"HSK 3"},
"花":{p:"huā",d:"flower; to spend (money, time)",l:"HSK 3"},
"画":{p:"huà",d:"to draw; painting",l:"HSK 3"},
"环境":{p:"huánjìng",d:"environment; surroundings",l:"HSK 3"},
"黄河":{p:"Huáng Hé",d:"the Yellow River",l:"HSK 3"},
"回答":{p:"huídá",d:"to answer; to reply",l:"HSK 3"},
"几乎":{p:"jīhū",d:"almost; nearly",l:"HSK 3"},
"极":{p:"jí",d:"extremely; utmost",l:"HSK 3"},
"季节":{p:"jìjié",d:"season",l:"HSK 3"},
"检查":{p:"jiǎnchá",d:"to check; to examine",l:"HSK 3"},
"简单":{p:"jiǎndān",d:"simple; easy",l:"HSK 3"},
"健康":{p:"jiànkāng",d:"health; healthy",l:"HSK 3"},
"见面":{p:"jiànmiàn",d:"to meet; to see someone",l:"HSK 3"},
"讲":{p:"jiǎng",d:"to speak; to tell; to explain",l:"HSK 3"},
"教":{p:"jiāo",d:"to teach",l:"HSK 3"},
"角":{p:"jiǎo",d:"corner; angle; horn",l:"HSK 3"},
"脚":{p:"jiǎo",d:"foot",l:"HSK 3"},
"接":{p:"jiē",d:"to pick up; to receive; to connect",l:"HSK 3"},
"街道":{p:"jiēdào",d:"street",l:"HSK 3"},
"结束":{p:"jiéshù",d:"to end; to finish",l:"HSK 3"},
"节目":{p:"jiémù",d:"program; show",l:"HSK 3"},
"节日":{p:"jiérì",d:"holiday; festival",l:"HSK 3"},
"解决":{p:"jiějué",d:"to solve; to resolve",l:"HSK 3"},
"借":{p:"jiè",d:"to borrow; to lend",l:"HSK 3"},
"经常":{p:"jīngcháng",d:"often; frequently",l:"HSK 3"},
"经过":{p:"jīngguò",d:"to pass by; through; after",l:"HSK 3"},
"经理":{p:"jīnglǐ",d:"manager",l:"HSK 3"},
"久":{p:"jiǔ",d:"long (time)",l:"HSK 3"},
"旧":{p:"jiù",d:"old; used; worn",l:"HSK 3"},
"刻":{p:"kè",d:"quarter (of an hour); to carve",l:"HSK 3"},
"客人":{p:"kèrén",d:"guest; visitor",l:"HSK 3"},
"口":{p:"kǒu",d:"mouth; (measure word for people)",l:"HSK 3"},
"哭":{p:"kū",d:"to cry",l:"HSK 3"},
"裤子":{p:"kùzi",d:"trousers; pants",l:"HSK 3"},
"蓝":{p:"lán",d:"blue",l:"HSK 3"},
"老":{p:"lǎo",d:"old; always",l:"HSK 3"},
"离开":{p:"líkāi",d:"to leave; to depart",l:"HSK 3"},
"历史":{p:"lìshǐ",d:"history",l:"HSK 3"},
"脸":{p:"liǎn",d:"face",l:"HSK 3"},
"辆":{p:"liàng",d:"(measure word for vehicles)",l:"HSK 3"},
"了解":{p:"liǎojiě",d:"to understand; to know well",l:"HSK 3"},
"留学":{p:"liúxué",d:"to study abroad",l:"HSK 3"},
"绿":{p:"lǜ",d:"green",l:"HSK 3"},
"马":{p:"mǎ",d:"horse",l:"HSK 3"},
"满意":{p:"mǎnyì",d:"satisfied; pleased",l:"HSK 3"},
"帽子":{p:"màozi",d:"hat; cap",l:"HSK 3"},
"米":{p:"mǐ",d:"meter; rice",l:"HSK 3"},
"拿":{p:"ná",d:"to take; to hold",l:"HSK 3"},
"奶奶":{p:"nǎinai",d:"grandma (father's mother)",l:"HSK 3"},
"南":{p:"nán",d:"south",l:"HSK 3"},
"难":{p:"nán",d:"difficult; hard",l:"HSK 3"},
"难过":{p:"nánguò",d:"sad; upset",l:"HSK 3"},
"年级":{p:"niánjí",d:"grade; year (in school)",l:"HSK 3"},
"年轻":{p:"niánqīng",d:"young",l:"HSK 3"},
"鸟":{p:"niǎo",d:"bird",l:"HSK 3"},
"爬山":{p:"páshān",d:"to climb a mountain; to hike",l:"HSK 3"},
"盘子":{p:"pánzi",d:"plate; dish",l:"HSK 3"},
"皮鞋":{p:"píxié",d:"leather shoes",l:"HSK 3"},
"瓶子":{p:"píngzi",d:"bottle",l:"HSK 3"},
"其他":{p:"qítā",d:"other; the rest",l:"HSK 3"},
"奇怪":{p:"qíguài",d:"strange; odd",l:"HSK 3"},
"起来":{p:"qǐlái",d:"to get up; to stand up",l:"HSK 3"},
"起飞":{p:"qǐfēi",d:"to take off (aircraft)",l:"HSK 3"},
"清楚":{p:"qīngchu",d:"clear; distinct",l:"HSK 3"},
"秋":{p:"qiū",d:"autumn; fall",l:"HSK 3"},
"裙子":{p:"qúnzi",d:"skirt; dress",l:"HSK 3"},
"热情":{p:"rèqíng",d:"warm; enthusiastic; passion",l:"HSK 3"},
"认为":{p:"rènwéi",d:"to think; to believe (that)",l:"HSK 3"},
"认真":{p:"rènzhēn",d:"serious; conscientious",l:"HSK 3"},
"容易":{p:"róngyì",d:"easy; likely to",l:"HSK 3"},
"伞":{p:"sǎn",d:"umbrella",l:"HSK 3"},
"生气":{p:"shēngqì",d:"to get angry",l:"HSK 3"},
"试":{p:"shì",d:"to try; to test",l:"HSK 3"},
"叔叔":{p:"shūshu",d:"uncle (father's younger brother)",l:"HSK 3"},
"树":{p:"shù",d:"tree",l:"HSK 3"},
"数学":{p:"shùxué",d:"mathematics",l:"HSK 3"},
"刷牙":{p:"shuāyá",d:"to brush one's teeth",l:"HSK 3"},
"双":{p:"shuāng",d:"pair; double",l:"HSK 3"},
"水平":{p:"shuǐpíng",d:"level; standard",l:"HSK 3"},
"司机":{p:"sījī",d:"driver",l:"HSK 3"},
"太阳":{p:"tàiyáng",d:"the sun",l:"HSK 3"},
"特别":{p:"tèbié",d:"especially; special",l:"HSK 3"},
"提高":{p:"tígāo",d:"to improve; to raise",l:"HSK 3"},
"体育":{p:"tǐyù",d:"physical education; sports",l:"HSK 3"},
"条":{p:"tiáo",d:"(measure word: long thin things)",l:"HSK 3"},
"头发":{p:"tóufa",d:"hair (on the head)",l:"HSK 3"},
"突然":{p:"tūrán",d:"suddenly; sudden",l:"HSK 3"},
"图书馆":{p:"túshūguǎn",d:"library",l:"HSK 3"},
"腿":{p:"tuǐ",d:"leg",l:"HSK 3"},
"万":{p:"wàn",d:"ten thousand",l:"HSK 3"},
"忘记":{p:"wàngjì",d:"to forget",l:"HSK 3"},
"为":{p:"wèi",d:"for; because of",l:"HSK 3"},
"为了":{p:"wèile",d:"in order to; for the sake of",l:"HSK 3"},
"位":{p:"wèi",d:"(polite measure word for people)",l:"HSK 3"},
"文化":{p:"wénhuà",d:"culture",l:"HSK 3"},
"西":{p:"xī",d:"west",l:"HSK 3"},
"夏":{p:"xià",d:"summer",l:"HSK 3"},
"香蕉":{p:"xiāngjiāo",d:"banana",l:"HSK 3"},
"相信":{p:"xiāngxìn",d:"to believe; to trust",l:"HSK 3"},
"向":{p:"xiàng",d:"toward; to face",l:"HSK 3"},
"像":{p:"xiàng",d:"to resemble; like; image",l:"HSK 3"},
"小心":{p:"xiǎoxīn",d:"to be careful; watch out",l:"HSK 3"},
"校长":{p:"xiàozhǎng",d:"principal; headmaster",l:"HSK 3"},
"新闻":{p:"xīnwén",d:"news",l:"HSK 3"},
"新鲜":{p:"xīnxiān",d:"fresh",l:"HSK 3"},
"信用卡":{p:"xìnyòngkǎ",d:"credit card",l:"HSK 3"},
"行李箱":{p:"xínglixiāng",d:"suitcase",l:"HSK 3"},
"熊猫":{p:"xióngmāo",d:"panda",l:"HSK 3"},
"要求":{p:"yāoqiú",d:"to demand; requirement",l:"HSK 3"},
"爷爷":{p:"yéye",d:"grandpa (father's father)",l:"HSK 3"},
"一共":{p:"yígòng",d:"altogether; in total",l:"HSK 3"},
"一会儿":{p:"yíhuìr",d:"a little while; in a moment",l:"HSK 3"},
"一样":{p:"yíyàng",d:"the same; alike",l:"HSK 3"},
"一般":{p:"yìbān",d:"ordinary; generally",l:"HSK 3"},
"一边":{p:"yìbiān",d:"one side; while (doing)",l:"HSK 3"},
"饮料":{p:"yǐnliào",d:"drink; beverage",l:"HSK 3"},
"影响":{p:"yǐngxiǎng",d:"to affect; influence",l:"HSK 3"},
"游戏":{p:"yóuxì",d:"game",l:"HSK 3"},
"有名":{p:"yǒumíng",d:"famous; well-known",l:"HSK 3"},
"又":{p:"yòu",d:"again; also",l:"HSK 3"},
"遇到":{p:"yùdào",d:"to run into; to encounter",l:"HSK 3"},
"元":{p:"yuán",d:"yuan (unit of currency)",l:"HSK 3"},
"愿意":{p:"yuànyì",d:"to be willing; to want to",l:"HSK 3"},
"月亮":{p:"yuèliang",d:"the moon",l:"HSK 3"},
"越":{p:"yuè",d:"the more (越…越…)",l:"HSK 3"},
"张":{p:"zhāng",d:"(measure word: flat things); Zhang",l:"HSK 3"},
"照顾":{p:"zhàogù",d:"to look after; to take care of",l:"HSK 3"},
"照相机":{p:"zhàoxiàngjī",d:"camera",l:"HSK 3"},
"中文":{p:"Zhōngwén",d:"Chinese (language)",l:"HSK 3"},
"中间":{p:"zhōngjiān",d:"middle; between",l:"HSK 3"},
"终于":{p:"zhōngyú",d:"finally; at last",l:"HSK 3"},
"种":{p:"zhǒng",d:"kind; type; (measure word)",l:"HSK 3"},
"重要":{p:"zhòngyào",d:"important",l:"HSK 3"},
"周末":{p:"zhōumò",d:"weekend",l:"HSK 3"},
"主要":{p:"zhǔyào",d:"main; principal",l:"HSK 3"},
"注意":{p:"zhùyì",d:"to pay attention; to be careful",l:"HSK 3"},
"自己":{p:"zìjǐ",d:"oneself; own",l:"HSK 3"},
"总是":{p:"zǒngshì",d:"always",l:"HSK 3"},
"嘴":{p:"zuǐ",d:"mouth",l:"HSK 3"},
"最后":{p:"zuìhòu",d:"last; final; in the end",l:"HSK 3"},
"作业":{p:"zuòyè",d:"homework; assignment",l:"HSK 3"}
};
