/* ===== Story essentials (70 words) — the adult-drama vocabulary HSK 1-3 lacks ===== */
const VOCAB_STORY={
"生活":{p:"shēnghuó",d:"life; to live",l:"story"},
"感情":{p:"gǎnqíng",d:"feelings; emotional relationship",l:"story"},
"心":{p:"xīn",d:"heart; mind",l:"story"},
"床":{p:"chuáng",d:"bed",l:"story"},
"夜":{p:"yè",d:"night",l:"story"},
"梦":{p:"mèng",d:"dream",l:"story"},
"醒":{p:"xǐng",d:"to wake up; to sober up",l:"story"},
"酒":{p:"jiǔ",d:"alcohol; liquor",l:"story"},
"醉":{p:"zuì",d:"drunk",l:"story"},
"烟":{p:"yān",d:"cigarette; smoke",l:"story"},
"抽":{p:"chōu",d:"to smoke; to pull out",l:"story"},
"抱":{p:"bào",d:"to hug; to hold",l:"story"},
"吻":{p:"wěn",d:"to kiss; a kiss",l:"story"},
"亲":{p:"qīn",d:"to kiss; close; dear",l:"story"},
"摸":{p:"mō",d:"to touch; to feel",l:"story"},
"脱":{p:"tuō",d:"to take off (clothes)",l:"story"},
"靠":{p:"kào",d:"to lean on; to rely on",l:"story"},
"推":{p:"tuī",d:"to push",l:"story"},
"拉":{p:"lā",d:"to pull",l:"story"},
"抓":{p:"zhuā",d:"to grab; to seize",l:"story"},
"喊":{p:"hǎn",d:"to shout; to yell",l:"story"},
"骂":{p:"mà",d:"to scold; to curse",l:"story"},
"吵架":{p:"chǎojià",d:"to argue; to have a fight",l:"story"},
"沉默":{p:"chénmò",d:"silence; to be silent",l:"story"},
"眼泪":{p:"yǎnlèi",d:"tears",l:"story"},
"难受":{p:"nánshòu",d:"to feel awful; unbearable",l:"story"},
"心疼":{p:"xīnténg",d:"to ache for someone; to feel bad",l:"story"},
"后悔":{p:"hòuhuǐ",d:"to regret",l:"story"},
"失望":{p:"shīwàng",d:"disappointed",l:"story"},
"讨厌":{p:"tǎoyàn",d:"to dislike; annoying",l:"story"},
"恨":{p:"hèn",d:"to hate",l:"story"},
"疯":{p:"fēng",d:"crazy; mad",l:"story"},
"孤单":{p:"gūdān",d:"lonely",l:"story"},
"尴尬":{p:"gāngà",d:"awkward; embarrassed",l:"story"},
"脾气":{p:"píqi",d:"temper",l:"story"},
"性格":{p:"xìnggé",d:"personality; character",l:"story"},
"面子":{p:"miànzi",d:"face; social standing",l:"story"},
"骗":{p:"piàn",d:"to lie to; to deceive",l:"story"},
"秘密":{p:"mìmì",d:"secret",l:"story"},
"躲":{p:"duǒ",d:"to hide; to avoid",l:"story"},
"偷":{p:"tōu",d:"to steal; secretly",l:"story"},
"出轨":{p:"chūguǐ",d:"to cheat (in a relationship)",l:"story"},
"情人":{p:"qíngrén",d:"lover",l:"story"},
"离婚":{p:"líhūn",d:"to divorce",l:"story"},
"单身":{p:"dānshēn",d:"single; unmarried",l:"story"},
"相亲":{p:"xiāngqīn",d:"to go on a matchmaking date",l:"story"},
"怀孕":{p:"huáiyùn",d:"to be pregnant",l:"story"},
"承认":{p:"chéngrèn",d:"to admit; to acknowledge",l:"story"},
"答应":{p:"dāying",d:"to promise; to agree to",l:"story"},
"原谅":{p:"yuánliàng",d:"to forgive",l:"story"},
"解释":{p:"jiěshì",d:"to explain",l:"story"},
"等待":{p:"děngdài",d:"to wait for",l:"story"},
"舍不得":{p:"shěbude",d:"to be reluctant to part with",l:"story"},
"受不了":{p:"shòubuliǎo",d:"can't stand it",l:"story"},
"忍":{p:"rěn",d:"to endure; to hold back",l:"story"},
"够":{p:"gòu",d:"enough",l:"story"},
"差不多":{p:"chàbuduō",d:"almost; about the same",l:"story"},
"本来":{p:"běnlái",d:"originally; at first",l:"story"},
"结果":{p:"jiéguǒ",d:"result; in the end",l:"story"},
"命":{p:"mìng",d:"life; fate",l:"story"},
"麻烦":{p:"máfan",d:"trouble; troublesome",l:"story"},
"危险":{p:"wēixiǎn",d:"dangerous; danger",l:"story"},
"安全":{p:"ānquán",d:"safe; safety",l:"story"},
"老家":{p:"lǎojiā",d:"hometown; family home",l:"story"},
"房贷":{p:"fángdài",d:"mortgage",l:"story"},
"轻":{p:"qīng",d:"light; gentle; softly",l:"story"},
"重":{p:"zhòng",d:"heavy; serious",l:"story"},
"深":{p:"shēn",d:"deep",l:"story"},
"温柔":{p:"wēnróu",d:"gentle; tender",l:"story"}
};
